### ISSUE TITLE
synchronizing EEGs and audio stimuli

### ISSUE THREAD

**Issue by franciscoaraposo** [sstober/openmiir#1]
Hi,

I was able to read the EEG data, bandpass it, and downsample it. I am assuming that the "RAW" data provided by your links is already referenced and that bad channel rejection has already been performed (the notebooks provided do suggest that the data was saved after doing those steps).

Then, I loaded the ICA components and computed the ICA components of the filtered, downsampled data.

Now, I want to split the final array into arrays that are synchronized with the audio stimuli. However, I cannot seem to be able to find the info that maps the EEG signal to the stimuli. The stim channel has some data, but it seems to be about the beats (as opposed to stimulus ID, start time, and end time). I need to know exactly when a specific stimulus starts (and when it ends), for every stimuli.

Thanks in advance for your attention,
Francisco

NOTE: Due to the fact that deepthought has several dependencies I don't want to install, I am using MNE directly for this.

**Comment by sstober** [comment]
Hi Francisco,

the stim channel contains markers for trials, audio onsets and pressed
keys. Audio onsets are from the StimTracker box and thus more precise.

Here's a code snippet to help you decode event IDs:
https://github.com/sstober/openmiir-rl-2016/blob/master/openmiir/events.py#L21

This functions helps to preprocess the markers as needed:
https://github.com/sstober/openmiir-rl-2016/blob/master/openmiir/preprocessing/events.py#L442

For a full pipeline to get synchronized trial epochs see:
https://github.com/sstober/openmiir-rl-2016/blob/master/1%20RAW%20Dataset%20Preparation%20512Hz.ipynb

I hope that helps. Let me know if you got further questions!

Cheers,
Sebastian

**Comment by franciscoaraposo** [comment]
I have a question: what is a trial epoch?

As far as I understand, you have a continuous stream of EEG data for each subject. So... Is an epoch just an arbitrary split, according to some event (like the playing of an audio stimulus), of that stream?

**Comment by sstober** [comment]
A trial epoch (as I used it) starts at a trial onset marker (I used the audio onsets when available). The duration depends on what you want to do. The length of the stimuli is known but it is different for each stimulus. You can either have epochs that correspond to the full audio stimulus but vary in length (e.g. for stimulus reconstruction experiments). Or you can cut of at the length of the shortest stimulus if they need to have the same length (e.g. for stimulus recognition experiments).

**Comment by franciscoaraposo** [comment]
By audio onset you mean the beginning of audio playback? For now, I want to
split the recordings only for the full stimulus duration... I can worry
about cutting later.

Also, for instance, I've noticed there are 5 trials for condition 1 -
stimulus 1 pair (in subject P01). Does this mean that subject P01 listened
to stimulus 1 in that condition 5 times?

The whole EEG signal (for subject P01 at least) is longer than 80 minutes.
I suppose this means the subject was being recorded non-stop this whole
time. Did he/she open his/her eyes or made any kind of movements? Can you
point to a paper where I can read about these experimental setup details?

Thank you,
Francisco

**Comment by franciscoaraposo** [comment]
Also, why did you exclude subject P05?

**Comment by sstober** [comment]
The paper about the experiment and the dataset is listed in the readme file of this repository. You'll find all details there. Here's a direct link: http://ismir2015.uma.es/articles/224_Paper.pdf
I also recommend having a look at this code repository https://github.com/sstober/openmiir-rl-2016/ and the respective paper (listed in the readme).

**Comment by Amirshm** [comment]
Hello, can anyone help me about converting fif to mat file ?
